tree_sitter_v/grammar.cjs
tree_sitter_v/src/grammar.json

clean cache test by `server/completion/CompletionResultSet.v`

[tree_sitter_v] fix qualified type

---

.github/workflows/nightly_release.yml

I'll let it run first on the main brach of the fork.

ci: fix binary path in nightly ci

---

.github/workflows/analyzer_tests.yml
tests/analyzer_test.v
tests/bench.v
tests/completion.v
tests/definitions.v
tests/documentation.v
tests/implementations.v
tests/supers.v
tests/types.v

With the change analyzer tests will also be run if `v test .` is run in the project root and are directory independent.
Due to current issues with V's `-stats` flag, it currently won't print more details when used with test runs. To get an extended overview - same as running the tests with `cd tests && v run .`. Execute the tests via `v tests/analyzer_test.v`

test: update tests to run with `v test`

---

.github/workflows/release.yml

The PR adds a change mentioned some weeks ago https://github.com/v-analyzer/v-analyzer/pull/83#issuecomment-1856432383. Upon creating a release tag the asset upload will be automated via the workflow. This reduces effort and helps with potential safety concerns.
Also since it's the debug build that is uploaded to the nightly tags the nightly assets were used for the last version release, the version releases with this workflow will now be release builds.

ci: extend release workflow; automate assets uploads on tag creation

---

analyzer/psi/doc_comment_extractor.v

Simplifying, hoping to make the code semantically easier to follow for maintainability, and removing a repeated variable declaration out of a loop where it is not necessary.

refactor: simplify doc_comment_extractor, slightly reduce load

---

.github/workflows/analyzer_tests.yml
.github/workflows/version_test.vv
build.vsh
metadata/metadata.v

The PR restores the functionality of the version command to its state before a regression after eae3f91.
A test to verify the version and to help to prevent further regression is added.

fix: version regression, add test

---

config/constants.v
server/general.v

The changes add a version-aware cache. This fixes the issue where an old cache would prevent updates and bug fixes from becoming visible to users.
<details>
<summary><i>obsolete</i></summary>
The versioning follows the same scheme as we do for the metadata/stubs. But instead of using a hardcoded version for the metadata(which is handled separately and changes less often) the changes in the PR add a more dynamic handling for the analyzer's indexing cache based on the build commit. This should be appropriate as it is affected by most commits to the project.
Refs to stubs versioning:
- setup: https://github.com/vlang/v-analyzer/blob/44c804decd62b77a149b5049e1c9f5d9b97f50cf/server/general.v#L345
- version file: https://github.com/vlang/v-analyzer/blob/44c804decd62b77a149b5049e1c9f5d9b97f50cf/c …

feat: use build version aware caching

---

analyzer/psi/doc_comment_extractor.v

Allow for inline struct field comments. Comments above a struct field are prioritised.
Adds a fast track exit if comments has a length of 0.

feat: add inline struct field comments

---

.gitattributes

Removes the `vendored` label from tree_sitter_v. The module is a part of the project that is actively developed inside the project and not really something "vendored". The tree_sitter_v module has it's own `.gitattributes` file that excludes generated code.
It would result in the following
Imho it's preferable to display the linguistics of the code base like this.

chore: don't label tree_sitter_v as vendored in `.gitattributes`

---

src/analyzer/psi/Comment.v
src/analyzer/psi/EnumFieldDeclaration.v
src/analyzer/psi/FieldDeclaration.v
src/analyzer/psi/doc_comment_extractor.v
src/analyzer/psi/element_factory.v
tree_sitter_v/bindings/node_types.v
tree_sitter_v/grammar.js
tree_sitter_v/queries/helix.highlights.scm
tree_sitter_v/queries/highlights.scm
tree_sitter_v/src/grammar.json
tree_sitter_v/src/node-types.json
tree_sitter_v/test/corpus/comments.txt
tree_sitter_v/test/corpus/function_declaration.txt
tree_sitter_v/test/corpus/interface_declaration.txt
tree_sitter_v/test/corpus/is_as_expression.txt
tree_sitter_v/test/corpus/module_clause.txt
tree_sitter_v/test/corpus/select_expression.txt
tree_sitter_v/test/corpus/struct_declaration.txt
tree_sitter_v/test/corpus/type_declaration.txt

Detaches line and block comments. E.g. when extracting doc comments analyzer can now differentiate for LineComments

tree-sitter: rewrite comment grammar, detach line- and block comments

---

tree_sitter_v/bindings/node_types.v
tree_sitter_v/grammar.js
tree_sitter_v/src/grammar.json
tree_sitter_v/src/node-types.json
tree_sitter_v/test/corpus/comments.txt

There are still several cases where comment parsing might run into errors. This PR approaches to fix some of them and to extend tests.

tree-sitter: further improve parsing of nested comments, extend tests

---

tree_sitter_v/bindings/node_types.v
tree_sitter_v/grammar.js
tree_sitter_v/src/grammar.json
tree_sitter_v/src/node-types.json
tree_sitter_v/test/corpus/string_literal.txt

Until now when encountering a doller sign in a string literal the parser run into an error. An example how this impacted highlighting:
Current:
Updated:

tree-sitter: fix parser error on unescaped dollar identifier in string literals, add test

---

build.vsh

analyzer: fix build for paths with spaces

---

src/server/progress/progress.v

The end message that prints the indexing progress doesn't pass a percentage anymore, which result in showing a 0% when the indexing finishes. The method is only called once after the indexing has really finished, so we can add the 100 as percentage field here.
*Screenshots below show the result on the bottom right*
|Current|Updated|
|:-:|:-:|
|![Screenshot_20240405_135952](https://github.com/vlang/v-analyzer/assets/34311583/095d45b2-56c9-446a-b0f3-a9905804954a)|![Screenshot_20240405_135952 (1)](https://github.com/vlang/v-analyzer/assets/34311583/0b9f9bab-1eda-470a-887f-c87cf646d065)|

analyzer: fix work progress shown as 0% when finishing indexing

---

src/server/general.v
src/server/language_server.v

The PR reworks path handling by using a `paths` child struct on the `LanguageServer`. vpaths will be set up during the language server setup process and become easily accessible throughout the session.
This helps to remove things like calling the `compiler_path()` function and calculating the vexe path on e.g. every request to a tool (like formatting on save). The same goes for repetitive calls of `vmodules_root()` and `vlib_root()`. Instead, the paths are just available via `ls.paths.vexe` `ls.paths.vlib_root` `ls.paths.vmodules_root`.

analyzer: rework path handling to simplify and reduce load

---

tree_sitter_v/grammar.js
tree_sitter_v/src/grammar.json
tree_sitter_v/test/corpus/if_expression.txt

- support `{ f();g();h(); }`
- minimal cleanup

[tree_sitter] minimal cleanup and add `;` support of block

---

src/server/general.v

The second line code `ls.paths.vmodules_root` path has not been set yet.So replace it with `vmodules_root` should be correct.
```v
// src/server/general.v
vmodules_root := os.vmodules_dir()
if !os.is_dir(ls.paths.vmodules_root) {
return error('Failed to find vmodules path')
}
ls.paths.vmodules_root = vmodules_root
```
```v
// src/server/general.v
vmodules_root := os.vmodules_dir()
if !os.is_dir(vmodules_root) {
return error('Failed to find vmodules path')
}
ls.paths.vmodules_root = vmodules_root
```

fix-setup_vpaths

---

.github/workflows/analyzer_tests.yml
.github/workflows/lint.yml

Splits the formatting verification into a separate workflow since there is no need to test if v fmt works on every platform in v-analyzer.

ci: use dedicated lint workflow to verify formatting

---

src/loglib/Logger.v
src/server/protocol/Client.v
src/server/setup_test.v

To test custom paths and errors the test currently redirects the output of the global logger that is defined in the loglib.
The test can be simplified when the severs initialization and setup process has progressed in it's error handling. For now, the used approach should work for asserting that paths have been set properly.

test: add test for toolchain path setup

---

src/server/general.v
src/server/setup_test.v

Solidifies and clarifies the setup process. Also has better client reporting.

analyzer: improve setup, extend client and log messages

---

src/server/documentation/provider.v
src/server/general.v

When the `VMODULES` environment variable is defined, other module paths need to be added to the index so that lsp can parse them correctly.
* dir -> escaped
* dir -> wrapper as code block

analyzer: add module index paths and wrapper module path as code block

---

install.vsh

`v install` should not be concerned with compilation flags.
And the actual compiler is determined by `build.vsh`:
<details>
```
PS C:\Users\***\.config\v-analyzer> $Env:CC = 'clang'
PS C:\Users\***\.config\v-analyzer> v .\install.vsh up --nightly
Installing latest nightly version...
Updating v-analyzer sources...
✓ Successfully updated v-analyzer sources
Building v-analyzer...
✓ Dependencies for v-analyzer installed successfully
Building v-analyzer at commit: 7e11a6f, build time: 2024-06-15 01:17:19 ...
✓ Prepared output directory
Building v-analyzer in debug mode, using: "E:\Programs\v\v.exe" "C:\Users\***\.config\v-analyzer\sources" -o "./bin/v-analyzer.exe" -no-parallel -cc clang  -g
To build in release mode, run v build.vsh release
Release mode is recommended for production use. At …
```

chore: remove useless `compiler_flag` and copy `.exe` on windows

---

src/lsp/diagnostics.v

Makes it comply with the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#codeDescription)
Fixes https://github.com/lv37/zed-v/issues/8

analyzer: Fix `code_description`

---

install.vsh
src/analyzer/index/IndexDeserializer.v
src/analyzer/index/IndexingRoot.v
src/bytes/serialization_test.v
src/jsonrpc/server.v
src/server/code_lens/CodeLensVisitor.v
src/server/completion/providers/ReferenceCompletionProcessor.v
src/server/diagnostics.v
src/server/features_hover.v
src/server/file_diff/Diff.v
src/server/general.v
src/server/hints/InlayHintsVisitor.v
src/server/inspections/compiler/utils.v
src/server/tform/tform.v
src/testing/TestFixture.v

This PR format all the files with the new vfmt.

format all the files with the new vfmt

---

src/check-updates.v
src/up.v
src/utils.v

Merge creation of `v-analyzer` vtmp directory in `src/utils.v`, function `download_install_vsh` => called by `check-updates` and `up` commands.

analyzer: merge creation of vtmp directory for check-updates/up commands

---

README.md

- add URL for mason registry
- add URL for mason-lspconfig.nvim plugin (':LspInstall' command)
- add URL for mason.nvim plugin (':MasonInstall v_analyzer' command)

docs: fix for Neovim LSP/Mason

---

src/up.v
src/utils.v

Move const used in `download_install_vsh` function from `src/up.v` to `src/utils.v` and define them private

analyzer: move const used to download install.vsh script

---

src/server/features_formatting.v
src/server/features_formatting_test.v

fix #128
vfmt on large files fills the stdout output buffer but v-analyzer does not read the buffer until vfmt exits.

fix hanging on windows

---

tree_sitter_v/grammar.js
tree_sitter_v/package.json
tree_sitter_v/src/grammar.json
tree_sitter_v/src/node-types.json
tree_sitter_v/src/tree_sitter/alloc.h
tree_sitter_v/src/tree_sitter/parser.h
tree_sitter_v/test/corpus/anon_struct.txt
tree_sitter_v/test/corpus/call_expression.txt
tree_sitter_v/test/corpus/function_literal.txt
tree_sitter_v/test/corpus/type_initializer.txt
tree_sitter_v/tree-sitter.json

Changes Tree-Sitter `field_name` to contain a `reference_expression`.
On top of https://github.com/vlang/v-analyzer/pull/134

Fix goto definition for field names.

---

.github/workflows/release.yml
build.vsh

Both the macos-arm64 and macos-x86_64 targets were building arm64 binaries. This fixes it.

Fix wrong macos target in release CI

---

src/utils.v

Hi, so the up thing calls http.download on a static page, which seems to bug everything.
I dont know if its intended or if its a bug in the net.http module tho. but this fixes it.

Fixed v-analyzer up

---

src/server/inspections/compiler/utils.v

Fixed the V compiler hanging in some cases.

Fix: Use `os.execute` instead of `os.Process` to fix instability

---

editors/code/src/bootstrap.ts

If the v-analyzer path is not set manually, realpathSync throws an exception, preventing the plugin from working properly.

fix:get server binary realpath when from PATH env

---

tree_sitter_v/bindings/node_types.v
tree_sitter_v/grammar.js
tree_sitter_v/src/grammar.json
tree_sitter_v/src/node-types.json
tree_sitter_v/src/tree_sitter/alloc.h
tree_sitter_v/src/tree_sitter/parser.h
tree_sitter_v/test/corpus/struct_declaration.txt

This PR changes tree-sitter-v grammar and adds implements interface syntax to struct declarations.
```vlang
struct Name implements Interface, qualifier.Interface2 {
name string
}
```

Add implements grammar
